import type { AminoAcidInfo } from '../types/biology';

export const AMINO_ACID_DEFINITIONS: Record<string, AminoAcidInfo> = {
  Met: {
    name: 'Methionine (Start)',
    threeLetter: 'Met',
    oneLetter: 'M',
    property: 'Nonpolar',
    color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    isStart: true,
    description: 'The universal START codon (AUG) in protein synthesis. Carries sulfur.',
  },
  Stop: {
    name: 'Stop Codon',
    threeLetter: 'Stop',
    oneLetter: '*',
    property: 'Special / Stop',
    color: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
    isStop: true,
    description: 'Signals the ribosome to release the completed polypeptide chain.',
  },
  Phe: {
    name: 'Phenylalanine',
    threeLetter: 'Phe',
    oneLetter: 'F',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Aromatic amino acid found in many proteins and artificial sweeteners.',
  },
  Leu: {
    name: 'Leucine',
    threeLetter: 'Leu',
    oneLetter: 'L',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Essential branched-chain amino acid critical for muscle protein synthesis.',
  },
  Ile: {
    name: 'Isoleucine',
    threeLetter: 'Ile',
    oneLetter: 'I',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Essential branched-chain amino acid assists with wound healing and energy.',
  },
  Val: {
    name: 'Valine',
    threeLetter: 'Val',
    oneLetter: 'V',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Essential branched-chain amino acid helping maintain metabolic balance.',
  },
  Ser: {
    name: 'Serine',
    threeLetter: 'Ser',
    oneLetter: 'S',
    property: 'Polar',
    color: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    description: 'Polar amino acid with a hydroxyl group, often phosphorylated.',
  },
  Pro: {
    name: 'Proline',
    threeLetter: 'Pro',
    oneLetter: 'P',
    property: 'Nonpolar',
    color: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    description: 'Unique cyclic structure introduces rigid kinks into peptide backbones.',
  },
  Thr: {
    name: 'Threonine',
    threeLetter: 'Thr',
    oneLetter: 'T',
    property: 'Polar',
    color: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    description: 'Essential polar amino acid supporting immune health and nervous system.',
  },
  Ala: {
    name: 'Alanine',
    threeLetter: 'Ala',
    oneLetter: 'A',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Simple and nonpolar, plays a key role in the glucose-alanine cycle.',
  },
  Tyr: {
    name: 'Tyrosine',
    threeLetter: 'Tyr',
    oneLetter: 'Y',
    property: 'Polar',
    color: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    description: 'Precursor for dopamine, epinephrine, and thyroid hormones.',
  },
  His: {
    name: 'Histidine',
    threeLetter: 'His',
    oneLetter: 'H',
    property: 'Basic',
    color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    description: 'Positively charged (basic) residue frequently found in catalytic enzyme active sites.',
  },
  Gln: {
    name: 'Glutamine',
    threeLetter: 'Gln',
    oneLetter: 'Q',
    property: 'Polar',
    color: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    description: 'Most abundant amino acid in the bloodstream; crucial nitrogen donor.',
  },
  Asn: {
    name: 'Asparagine',
    threeLetter: 'Asn',
    oneLetter: 'N',
    property: 'Polar',
    color: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    description: 'First amino acid isolated from asparagus juice in 1806.',
  },
  Lys: {
    name: 'Lysine',
    threeLetter: 'Lys',
    oneLetter: 'K',
    property: 'Basic',
    color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    description: 'Essential basic amino acid vital for collagen formation and calcium absorption.',
  },
  Asp: {
    name: 'Aspartic Acid',
    threeLetter: 'Asp',
    oneLetter: 'D',
    property: 'Acidic',
    color: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    description: 'Negatively charged (acidic) residue involved in the urea cycle.',
  },
  Glu: {
    name: 'Glutamic Acid',
    threeLetter: 'Glu',
    oneLetter: 'E',
    property: 'Acidic',
    color: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    description: 'Key neurotransmitter precursor and cellular energy substrate.',
  },
  Cys: {
    name: 'Cysteine',
    threeLetter: 'Cys',
    oneLetter: 'C',
    property: 'Special / Stop',
    color: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    description: 'Forms covalent disulfide bonds (bridges) that stabilize 3D protein structures.',
  },
  Trp: {
    name: 'Tryptophan',
    threeLetter: 'Trp',
    oneLetter: 'W',
    property: 'Nonpolar',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    description: 'Largest amino acid with indole ring; biological precursor to serotonin and melatonin.',
  },
  Arg: {
    name: 'Arginine',
    threeLetter: 'Arg',
    oneLetter: 'R',
    property: 'Basic',
    color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    description: 'Strongly basic amino acid that produces nitric oxide to regulate blood flow.',
  },
  Gly: {
    name: 'Glycine',
    threeLetter: 'Gly',
    oneLetter: 'G',
    property: 'Nonpolar',
    color: 'bg-slate-500/20 text-slate-300 border-slate-500/40',
    description: 'The smallest and simplest amino acid; single hydrogen atom side chain allows high flexibility.',
  },
};

// Standard RNA Codon Table (64 codons)
export const GENETIC_CODE_TABLE: Record<string, string> = {
  // U
  UUU: 'Phe', UUC: 'Phe', UUA: 'Leu', UUG: 'Leu',
  UCU: 'Ser', UCC: 'Ser', UCA: 'Ser', UCG: 'Ser',
  UAU: 'Tyr', UAC: 'Tyr', UAA: 'Stop', UAG: 'Stop',
  UGU: 'Cys', UGC: 'Cys', UGA: 'Stop', UGG: 'Trp',

  // C
  CUU: 'Leu', CUC: 'Leu', CUA: 'Leu', CUG: 'Leu',
  CCU: 'Pro', CCC: 'Pro', CCA: 'Pro', CCG: 'Pro',
  CAU: 'His', CAC: 'His', CAA: 'Gln', CAG: 'Gln',
  CGU: 'Arg', CGC: 'Arg', CGA: 'Arg', CGG: 'Arg',

  // A
  AUU: 'Ile', AUC: 'Ile', AUA: 'Ile', AUG: 'Met',
  ACU: 'Thr', ACC: 'Thr', ACA: 'Thr', ACG: 'Thr',
  AAU: 'Asn', AAC: 'Asn', AAA: 'Lys', AAG: 'Lys',
  AGU: 'Ser', AGC: 'Ser', AGA: 'Arg', AGG: 'Arg',

  // G
  GUU: 'Val', GUC: 'Val', GUA: 'Val', GUG: 'Val',
  GCU: 'Ala', GCC: 'Ala', GCA: 'Ala', GCG: 'Ala',
  GAU: 'Asp', GAC: 'Asp', GAA: 'Glu', GAG: 'Glu',
  GGU: 'Gly', GGC: 'Gly', GGA: 'Gly', GGG: 'Gly',
};
